WIP Blog/comments
lmachens/hogwarts.gg pull request #19
Opened 2023-02-03 15:32 UTC by glazk0

**What changed ?**

- Added both comments migrations [first](https://github.com/glazk0/hogwarts.gg/blob/blog/comments/supabase/migrations/20230202170822_comments_permissions.sql), [second](https://github.com/glazk0/hogwarts.gg/blob/blog/comments/supabase/migrations/20230202171300_comments.sql)
- Added comments to Post (ui)
- Created CommentForm (ui)

Basically it works pretty well, for now it loads every comments whatever the language, it takes the group_ip xor post_id.

I'm still working about the delete / edit Icons function (if you have any suggestions)

I plan to make a comment Component to avoid repetition.

![image](https://user-images.githubusercontent.com/43091603/216642124-4bc39e1e-515a-4b7b-85ae-6c2da90b7e36.png)

2023-02-03 15:50 UTC, lmachens requested changes
Very nice, this will be wonderful 🤘

2023-02-03 15:50 UTC, lmachens commented on lib/comments.ts
> +}): Promise<Comment[]> => {
If it's `else-if` (only `postId` or `nodeId`, never both), you can add a union here:

```suggestion
}: {
  postId?: number | null;
} | {
  nodeId?: number | null;
}): Promise<Comment[]> => {
```

And it looks like you require one of them. This will make the `else` case with the Error obsolete:

```suggestion
}: {
  postId: number | null;
} | {
  nodeId: number | null;
}): Promise<Comment[]> => {
```

Now it's required to set `postId` or `nodeId`.

If you do that, you need to do the same for `useComments`

2023-02-03 15:50 UTC, lmachens commented on lib/hooks/use-comments.ts
> +    return useSWR(`comments/${postId || nodeId}`, () => getComments({ postId, nodeId }));
Be careful here if you use `postId || nodeId`. This will load wrong comments, if you first comments for node with ID 1 and load comments for post with ID 1 afterwards.
Instead, I would use `nodes/comments/1` and `posts/comments/1` (or something like this).

2023-02-03 15:50 UTC, lmachens commented on lib/i18n/dictionaries/de.json
> +    "aboutTheAuthor": "About the author",
```suggestion
    "aboutTheAuthor": "Über den Author",
```

2023-02-03 15:50 UTC, lmachens commented on lib/i18n/dictionaries/de.json
> +    "commentSubmit": "Submit"
```suggestion
    "commentSubmit": "Abschicken"
```

2023-02-03 15:50 UTC, lmachens commented on supabase/migrations/20230202171300_comments.sql
> +alter table "public"."comments" enable row level security;
> (I think I need to create policy for delete / edit for admin / moderator)

2023-02-03 15:50 UTC, lmachens commented on ui/CommentForm.tsx
> +              postId={post!.id}
Looks like it's prepared to support nodes and posts. This will fail for nodes.

2023-02-03 15:50 UTC, lmachens commented on ui/EditorInput.tsx
> +  }, [isSubmitting]);
Does this mean, that the content is set to an empty string if you submit the form?
What happens, when the submitting is failing and an error is thrown?

I guess it would make more sense to set `value` to an empty string instead.

2023-02-03 16:01 UTC, glazk0 commented on lib/comments.ts
> +}): Promise<Comment[]> => {
Oh that's pretty nice, totally forgot that we were able to do that!

2023-02-03 16:02 UTC, glazk0 commented on lib/hooks/use-comments.ts
> +    return useSWR(`comments/${postId || nodeId}`, () => getComments({ postId, nodeId }));
Ok! Just gonna split this one to distinct call refactoring it now will be better for future nodes comments.

2023-02-03 16:02 UTC, glazk0 commented on lib/i18n/dictionaries/de.json
> +    "aboutTheAuthor": "About the author",
Thanks!

2023-02-03 16:03 UTC, glazk0 commented on ui/CommentForm.tsx
> +              postId={post!.id}
Was about to add it! But yeah for now it supports only post.

2023-02-03 16:04 UTC, glazk0 commented on ui/EditorInput.tsx
> +  }, [isSubmitting]);
Yeah it does, at first I was messing with it to see how I could interact with it to refresh / delete the content.

2023-02-06 09:37 UTC, lmachens approved these changes
Looks good to me.
I pushed some changes (see commits).

What's not done yet (next pull requests):
- Delete images on comment deletion/editing (same for posts)
- Edit comments

2023-02-06 09:38 UTC, merged