Added webhook
lmachens/hogwarts.gg pull request #30
Opened 2023-02-07 22:12 UTC by glazk0

Check the code, also check if the getURL() is used in the right way (didn't know if you set en by default in your .env).

Otherwise it should be good, I've setup the webhooks in Supabase, you just need to setup the Discord webhook and put it in the .env

Here is the result (the url will be provided in prod, Discord doesn't like localhost url)

<img width="537" alt="image" src="https://user-images.githubusercontent.com/43091603/217378618-21838f91-3e43-43d5-81c3-080d729f6bc7.png">

2023-02-08 20:07 UTC, lmachens requested changes
Good job!
Can you add a secret HTTP header to make sure, that this /api/webhooks/posts is called from somewhere else?
e.g. call the header `token`.
Then, create another environment variable, which uses the same token and verifies it on hook call.
I can add the environemnt variable on Vercel afterwards.

2023-02-08 20:07 UTC, lmachens commented on pages/api/webhooks/posts.ts
> +        url: getURL() + `${language}/blog/${slug}`,
This should work too. 
```suggestion
        url: getURL( `/${language}/blog/${slug}`),
```

2023-02-08 20:13 UTC, glazk0 commented on template.env
> +NEXT_PUBLIC_DISCORD_WEBHOOK_URL=YOUR_DISCORD_WEBHOOK_URL
Sure!

2023-02-10 09:27 UTC, lmachens commented on pages/api/webhooks/posts.ts
> +  if (!req.body.record && !req.body.old_record) {
If you require both, it should be 

```suggestion
  if (!req.body.record || !req.body.old_record) {
```

2023-02-10 09:27 UTC, lmachens commented on pages/api/webhooks/posts.ts
> +  }
I am not sure if it's good to return an error code to the supabase webhook.
Not sure, what happens, when it things it was failing.

If "published" is not changed to `true`, we could `200` (because it's a valid request).

```suggestion
  if (!published || old_published) {
    return res.status(200).json({ message: 'Post was not published' });
  }
```

2023-02-10 09:46 UTC, lmachens approved these changes
Good job!

2023-02-10 10:03 UTC, merged