feat/seo
lmachens/hogwarts.gg pull request #57
Opened 2023-02-28 19:48 UTC by glazk0

2023-03-02 16:24 UTC, lmachens requested changes
looks good, only a small issue

2023-03-02 16:24 UTC, lmachens commented on app/[lang]/blog/[slug]/page.tsx
> +      images: getURL(post.image!) || getURL('/assets/social.png'),
I think `getURL` will always return a string. Thus, the fallback will never called.

2023-03-02 16:26 UTC, glazk0 commented on app/[lang]/blog/[slug]/page.tsx
> +      images: getURL(post.image!) || getURL('/assets/social.png'),
So checking if it's blank would fix the issue?

2023-03-02 16:29 UTC, lmachens commented on app/[lang]/blog/[slug]/page.tsx
> +      images: getURL(post.image!) || getURL('/assets/social.png'),
`getURL(post.image || '/assets/social.png')`  should work

2023-03-02 19:54 UTC, glazk0 commented
There is a pnpm conflict but I let you fix it, don't wanna break stuff

2023-03-03 06:26 UTC, lmachens approved these changes
Good job!

2023-03-03 06:27 UTC, merged