Add Youtube to Blog
lmachens/hogwarts.gg pull request #9
Opened 2023-01-26 13:29 UTC by glazk0

Here is my first PR, still working on it, it's just to know if the way I'm doing stuff is good for you.

- Added @tiptap/extension-youtube to blog section
- Added **Delete** button to PostForm
- Added some informations in Blog post

2023-01-26 15:06 UTC, lmachens requested changes
Good job! It looks much better.
I added some comments.

2023-01-26 15:06 UTC, lmachens commented on app/dashboard/posts/page.tsx
> +                    })}
I really like the cards in the admin dashboard, but the dates lead to line-breaks.
Maybe remove the "time ago"?
![image](https://user-images.githubusercontent.com/10058950/214869924-003581f6-720c-4cbc-a50e-3c071006c7a3.png)

2023-01-26 15:06 UTC, lmachens commented on app/dashboard/posts/page.tsx
> +                  Writed by <span className="text-brand-500">{post.user_id!.username ? post.user_id!.username : 'Harry Potter' }</span>
If #10 is merged before this request, this fallback to "Harry Potter" won't be necessary anymore.

2023-01-26 21:34 UTC, lmachens approved these changes
Looks good!

2023-01-26 21:42 UTC, lmachens requested changes

2023-01-26 21:42 UTC, lmachens commented on app/blog/page.tsx
> +                <span className="font-semibold">{post.user_id!.username}</span>{' '}
This line leads to an error on deployment:

` Type error: Property 'username' does not exist on type 'string & ({ username: unknown; } | { username: unknown; }[])'.` 
Did you face the same issue?

I guess it's the best to check if `user_id` is really an object with `username` .
I am doing something similar in:
https://github.com/lmachens/hogwarts.gg/blob/19cfebb64c4d6cc7d6162e08b6c383da810c2da5/lib/users.ts#L26-L31

2023-01-26 22:52 UTC, glazk0 commented
Let me know if my solution is correct, also thought to maybe add the **User** type later since it's in the #10.

2023-01-27 17:39 UTC, lmachens approved these changes
Good job!
I refactored it a bit and found some missing unique indexes in the database.
With these indexes, we can make sure if an array or single object is returned.
Instead of TS casts, I am using assertions now, which leads to type safety too (but without uncaught errors, if we are wrong).

I renamed the inner joins and prepared a `user` in the posts (we might need need the avatar someday).

2023-01-27 17:40 UTC, merged